Mariana legacy css
CityOfBoston/patterns pull request #577
Opened 2021-07-22 19:26 UTC by mharoc

2021-07-30 15:49 UTC, phillipbentonkelly requested changes
Please apply the following changes
- The Quotes template needs work, the scaling and formatting doesn't match the component yet. Once you have it looking right add another with different text, text length to show what it looks like with longer text than expected
  - make the icon's default/max dimensions smaller
- rename the `quote` directory to exclude the spaces between, linking to [google's naming conventions](https://developers.google.com/style/filenames#:~:text=to%20file%20types-,Naming%20guidelines,in%20file%20and%20directory%20names.) as a good start/guide in general
- Add more flags, pref the other variants shown in [zero heights](https://zeroheight.com/7316f2c4a/p/192f88-flags/b/59bc45) excluding the `ico` one
- Use a formatter to make the code (specially the HTML/Handlebars templates) more readable. Prettier is the most used formatter, though I don't think works for these template but its works having for everything else <img width="272" alt="Screen Shot 2021-07-30 at 11 41 05 AM" src="https://user-images.githubusercontent.com/2627273/127677779-6d63c570-6a00-4089-8e9f-1510003f8505.png">
- End files in with a new (empty) line (\n)

2021-07-30 15:49 UTC, phillipbentonkelly commented on components/base/grid of quotes/gridofquotes.hbs
> +  </div>
End every file with an empty new line (\n).

2021-09-15 18:21 UTC, phillipbentonkelly requested changes
In Draft mode for Stella to take a look at again

2021-09-17 15:04 UTC, subaha-cob approved these changes
LGTM

2021-09-17 15:04 UTC, merged