Legacy css  carolyn  how to tab  issue556
CityOfBoston/patterns pull request #583
Opened 2021-08-12 15:54 UTC by carolyn-wang

**Branch for Issue #556 (UI updates for How-To page)**
Removed this task from my previous pull request (Legacy css Carolyn issues #551 #554 #556) and moved it here instead

2021-08-18 14:01 UTC, phillipbentonkelly approved these changes
LGTM

2021-08-18 14:01 UTC, phillipbentonkelly commented on components/blocks/how-to-tabs/how-to-tab/how-to-tab.hbs
> +{{/each}}
Check how you're ending these files, I see its yelling about 'no end of file' but its not doing it for others that end the same

2021-09-15 19:19 UTC, phillipbentonkelly requested changes
- Un-delete `tabs` (components/base/tabs/)
- Checkout package-lock.json
- Fix merge conflicts

2021-09-17 15:03 UTC, subaha-cob approved these changes
LGTM

2021-09-17 15:03 UTC, merged